/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { A2aAgentView, A2aStatusView } from './types.js'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6132615265676973747279 {
    discover: (signal?: AbortSignal) => Promise<RemoteResult<A2aAgentView[]>>
    login: (ak: string, sk: string) => Promise<RemoteResult<void>>
    logout: () => Promise<RemoteResult<void>>
    status: () => Promise<RemoteResult<A2aStatusView>>
  }
  interface TypertRemoteMap {
    'a2aRegistry/discover': (signal?: AbortSignal) => Promise<RemoteResult<A2aAgentView[]>>
    'a2aRegistry/login': (ak: string, sk: string) => Promise<RemoteResult<void>>
    'a2aRegistry/logout': () => Promise<RemoteResult<void>>
    'a2aRegistry/status': () => Promise<RemoteResult<A2aStatusView>>
  }
  interface TypertRemoteNamespaceMap {
    'a2aRegistry': TypertRemoteNamespace$6132615265676973747279
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
